# FETCH LABEL ARTICLES
GET http://localhost:3000/label/4


### fetch all labels
GET http://localhost:3000/label/all


### post label
POST   http://localhost:3000/label
Content-Type: application/json

{
    "name":"health"
}


### delete label 

DELETE http://localhost:3000/label/delete/1