### fetch BLOGS  
GET http://localhost:3000/api/blogs

### FETCH A BLOG WITH ID

GET http://localhost:3000/api/blogs/3


### FETCH LABEL BLOGS

GET http:///localhost:3000/api/Label



### DELETE A BLOG WITH ID

DELETE http://localhost:3000/api/blogs/16


### POST A NEW BLOG 

POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title" :"HAMID",
    "content":"HAMID ipsum Color sit amet consectetur adipisicing elit. Maxime mollitia Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia",
    "imgUrl":"",
    "labelId":1
}

### UPDATE ARTICLE

PATCH http://localhost:3000/api/blogs/2
Content-Type: application/json

{
    "id":6,
    "title":"COVID 19",
    "content":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia",
    "labelId":2,
}

