### GET ALL USERS 
GET http://localhost:3000/users/

### DELETE A USER
DELETE  http://localhost:300/users/remove/7

### POST A USER
POST http://localhost:3000/users/add
Content-Type:  application/json

{
    "email":"yassine@maraoui.me",
    "name":"yassin",
    "password":"1234"
}

